import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "@styles/global.css";
import Nav from "@components/Nav";
import Footer from "@components/Footer";

const lato = Lato({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Nikolay Gavazov",
  description: "Generated by Nikolay Gavazov",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={lato.className}>
        <header>
          <Nav />
        </header>
        <main className="app flex flex-col flex-1">{children}
        <div className="w-full h-full">
        <div id="stars"></div>
        <div id="stars2"></div>
        <div id="stars3"></div>
      </div>
        </main>
        <Footer />
      </body>
    </html>
  );
}
