import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";

const lato = Lato({weight:"400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Nikolay Gavazov",
  description: "Generated by Nikolay Gavazov",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={lato.className}>{children}</body>
    </html>
  );
}
